### ISSUE TITLE
wrong gradient

### ISSUE THREAD

**Issue by enkimute** [sincoon/levenberg-maquardt-example#2]
You have a mistake in your gradient. The partial derivative for temperature of the heater (first parameter) needs to be :

```
1.0 - exp(-par[2] * x);
```
and not :

```
1.0 + exp(-par[2] * x);
```

nb. It's also called 'Newtons law of cooling' ;)

**Comment by leechwort** [comment]
Hello! Thank you for your notice! Have you tested code with this change?

**Comment by enkimute** [comment]
yes I have .. it is far far far more efficient if you use the right gradient ;)

**Comment by leechwort** [comment]
Ok, fixed!

**Comment by enkimute** [comment]
All good.
